# Generated by Django 3.1.2 on 2020-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=280)),
                ('image_path', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
    ]
